#!/usr/bin/env bash
# Split the operator-facing repo-root .env into per-service env files so each
# container only receives the secrets it needs.
# Usage: ./scripts/split-env.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SRC="$PROJECT_ROOT/.env"

if [[ ! -f "$SRC" ]]; then
  echo "ERROR: Missing $SRC"
  exit 1
fi

get() {
  local key="$1"
  grep -E "^${key}=" "$SRC" | head -1 | cut -d= -f2- || true
}

write_file() {
  local dest="$1"
  shift
  {
    echo "# Generated by scripts/split-env.sh from .env — do not edit by hand."
    for key in "$@"; do
      local val
      val="$(get "$key")"
      if [[ -n "$val" ]]; then
        echo "${key}=${val}"
      fi
    done
  } > "$dest"
  echo "Wrote $dest"
}

write_file "$PROJECT_ROOT/.env.db" \
  DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD DB_ROOT_PASSWORD \
  MARIADB_DATABASE MARIADB_USER MARIADB_PASSWORD MARIADB_ROOT_PASSWORD

write_file "$PROJECT_ROOT/.env.api" \
  DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD DATABASE_URL \
  PORT NODE_ENV AUTH_SECRET API_AUTH_SECRET AUTH_ENABLED \
  AUTH_LOGIN_RATE_LIMIT_WINDOW_MS AUTH_LOGIN_RATE_LIMIT_MAX TRUST_PROXY \
  CORS_ORIGINS ALLOW_LOCALHOST_CORS_IN_PRODUCTION SEED_ADMIN_PASSWORD

write_file "$PROJECT_ROOT/.env.worker" \
  DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD DATABASE_URL \
  NODE_ENV WORKER_INTERVAL_MS AUTH_SECRET API_AUTH_SECRET

write_file "$PROJECT_ROOT/.env.frontend" \
  PORT HOST

# Frontend serve defaults to 9999; ensure PORT is set for the container.
if ! grep -q '^PORT=' "$PROJECT_ROOT/.env.frontend"; then
  echo "PORT=9999" >> "$PROJECT_ROOT/.env.frontend"
fi
